url: https://carolcupaslab.netlify.app/
# baseurl: /

# Site settings
title: Carol Cupas's LAB
email: hola@carolcupas.com
description: "Discover about my services, career and personal experiences. Let's meet and embark on an adventure to achieve goals we never imagined."


# Team names, titles and social links
people:
- name: Carol Cupas
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: CC
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: CC
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, stack-overflow, twitter, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/carolcupaspitti/
  - title: instagram
    url:
  - title: facebook
    url: 
  #- title: bitbucket 
  #  url: http://bitbucket.org/jekyll
  #- title: github
  #  url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Madrid, 28039
  - line: Spain

# Build settings
markdown: kramdown
permalink: pretty