url: https://www.carolcupas.com/
# baseurl: /

# HTTP header Content-Security-Policy during development with jekyll serve
# fix Access-Control-Allow-Origin (CORS origin) - only Localsite
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Site settings
title: Carol Cupas's Lab
email: hola@carolcupas.com
description: "Discover about my services, career and personal experiences. Let's meet and embark on an adventure to achieve goals we never imagined."
tagline: Creatividad, inspiración y asesoría para el diseño de páginas webs y contenido de redes sociales  
slogan: "Soluciones web para negocios digitales"

#logo-white: 'img/logos/CC_logo.png'
logo: 'img/logos/CC_logo.png'
favicon: 'img/icons/favicon.ico'
disqus: 'carolcupaslab'

#calendar_event: https://shorturl.at/dehmx
#form_comunidades: https://bit.ly/33QYNAX


reCAPTCHA_key: 6LdA-L0ZAAAAAJI_x0inm8igBL17L66xyYsbF3v-

# Team names, titles and social links
people:
- name: Carol Cupas
  pic: 1
  position: Director
  excerpt: I am passionate about technology, photography, graphic design, and nature. During 2020, I reinvented myself to offer consulting in web solutions according to the needs of companies such as the creation of the digital logo, website, social networks, professional email, data analytics, among others. These solutions aim to help companies have a presence in digital media to present their products and/or services online.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, stack-overflow, twitter, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/carolcupaspitti/
  - title: instagram
    url: https://www.instagram.com/carolcupas/
  - title: facebook
    url: https://www.facebook.com/carolcupaslab/
  #- title: twitter
  #  url: hhttps://twitter.com/
  #- title: bitbucket 
  #  url: http://bitbucket.org/jekyll
  #- title: github
  #  url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Madrid, 28039
  - line: Spain

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  # - jekyll-feed
  # - jekyll-paginate
  # - jekyll-sitemap
  # - jekyll-seo-tag
  # - jekyll-tidy
  #- jekyll-compress-images

